/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  OrderAddDTO,
  OrderDTOPagedResponseRequestResponse,
  OrderDTORequestResponse,
  RequestResponse,
} from '../models';
import {
    OrderAddDTOFromJSON,
    OrderAddDTOToJSON,
    OrderDTOPagedResponseRequestResponseFromJSON,
    OrderDTOPagedResponseRequestResponseToJSON,
    OrderDTORequestResponseFromJSON,
    OrderDTORequestResponseToJSON,
    RequestResponseFromJSON,
    RequestResponseToJSON,
} from '../models';

export interface ApiOrderCreateOrderPostRequest {
    orderAddDTO?: OrderAddDTO;
}

export interface ApiOrderGetOrderIdGetRequest {
    id: string;
}

export interface ApiOrderGetPageGetRequest {
    search?: string;
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class OrderApi extends runtime.BaseAPI {

    /**
     */
    async apiOrderCreateOrderPostRaw(requestParameters: ApiOrderCreateOrderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Order/CreateOrder`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrderAddDTOToJSON(requestParameters.orderAddDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiOrderCreateOrderPost(requestParameters: ApiOrderCreateOrderPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestResponse> {
        const response = await this.apiOrderCreateOrderPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiOrderGetOrderIdGetRaw(requestParameters: ApiOrderGetOrderIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDTORequestResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiOrderGetOrderIdGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Order/GetOrder/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDTORequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiOrderGetOrderIdGet(requestParameters: ApiOrderGetOrderIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDTORequestResponse> {
        const response = await this.apiOrderGetOrderIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiOrderGetPageGetRaw(requestParameters: ApiOrderGetPageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderDTOPagedResponseRequestResponse>> {
        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['Search'] = requestParameters.search;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['Page'] = requestParameters.page;
        }

        if (requestParameters.pageSize !== undefined) {
            queryParameters['PageSize'] = requestParameters.pageSize;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Order/GetPage`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderDTOPagedResponseRequestResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiOrderGetPageGet(requestParameters: ApiOrderGetPageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderDTOPagedResponseRequestResponse> {
        const response = await this.apiOrderGetPageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
