/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CartInfoDTO } from './CartInfoDTO';
import {
    CartInfoDTOFromJSON,
    CartInfoDTOFromJSONTyped,
    CartInfoDTOToJSON,
} from './CartInfoDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CartInfoDTORequestResponse
 */
export interface CartInfoDTORequestResponse {
    /**
     * 
     * @type {CartInfoDTO}
     * @memberof CartInfoDTORequestResponse
     */
    response?: CartInfoDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CartInfoDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the CartInfoDTORequestResponse interface.
 */
export function instanceOfCartInfoDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CartInfoDTORequestResponseFromJSON(json: any): CartInfoDTORequestResponse {
    return CartInfoDTORequestResponseFromJSONTyped(json, false);
}

export function CartInfoDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartInfoDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : CartInfoDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CartInfoDTORequestResponseToJSON(value?: CartInfoDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': CartInfoDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

