/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CartItemAddDTO
 */
export interface CartItemAddDTO {
    /**
     * 
     * @type {string}
     * @memberof CartItemAddDTO
     */
    productId?: string;
    /**
     * 
     * @type {number}
     * @memberof CartItemAddDTO
     */
    quantity?: number;
}

/**
 * Check if a given object implements the CartItemAddDTO interface.
 */
export function instanceOfCartItemAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CartItemAddDTOFromJSON(json: any): CartItemAddDTO {
    return CartItemAddDTOFromJSONTyped(json, false);
}

export function CartItemAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productId': !exists(json, 'productId') ? undefined : json['productId'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function CartItemAddDTOToJSON(value?: CartItemAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'productId': value.productId,
        'quantity': value.quantity,
    };
}

