/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CartItemDTOPagedResponse } from './CartItemDTOPagedResponse';
import {
    CartItemDTOPagedResponseFromJSON,
    CartItemDTOPagedResponseFromJSONTyped,
    CartItemDTOPagedResponseToJSON,
} from './CartItemDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CartItemDTOPagedResponseRequestResponse
 */
export interface CartItemDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {CartItemDTOPagedResponse}
     * @memberof CartItemDTOPagedResponseRequestResponse
     */
    response?: CartItemDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CartItemDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the CartItemDTOPagedResponseRequestResponse interface.
 */
export function instanceOfCartItemDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CartItemDTOPagedResponseRequestResponseFromJSON(json: any): CartItemDTOPagedResponseRequestResponse {
    return CartItemDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function CartItemDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : CartItemDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CartItemDTOPagedResponseRequestResponseToJSON(value?: CartItemDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': CartItemDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

