/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CartItemUpdateDTO
 */
export interface CartItemUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof CartItemUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof CartItemUpdateDTO
     */
    quantity?: number | null;
}

/**
 * Check if a given object implements the CartItemUpdateDTO interface.
 */
export function instanceOfCartItemUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CartItemUpdateDTOFromJSON(json: any): CartItemUpdateDTO {
    return CartItemUpdateDTOFromJSONTyped(json, false);
}

export function CartItemUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartItemUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function CartItemUpdateDTOToJSON(value?: CartItemUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'quantity': value.quantity,
    };
}

