/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CartInfoDTO
 */
export interface CartInfoDTO {
    /**
     * 
     * @type {string}
     * @memberof CartInfoDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof CartInfoDTO
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof CartInfoDTO
     */
    totalPrice?: number;
    /**
     * 
     * @type {Date}
     * @memberof CartInfoDTO
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CartInfoDTO
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the CartInfoDTO interface.
 */
export function instanceOfCartInfoDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CartInfoDTOFromJSON(json: any): CartInfoDTO {
    return CartInfoDTOFromJSONTyped(json, false);
}

export function CartInfoDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartInfoDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'totalPrice': !exists(json, 'totalPrice') ? undefined : json['totalPrice'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function CartInfoDTOToJSON(value?: CartInfoDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'size': value.size,
        'totalPrice': value.totalPrice,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

