/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CategoryDTO } from './CategoryDTO';
import {
    CategoryDTOFromJSON,
    CategoryDTOFromJSONTyped,
    CategoryDTOToJSON,
} from './CategoryDTO';

/**
 * 
 * @export
 * @interface CategoryDTOPagedResponse
 */
export interface CategoryDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof CategoryDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof CategoryDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<CategoryDTO>}
     * @memberof CategoryDTOPagedResponse
     */
    data?: Array<CategoryDTO> | null;
}

/**
 * Check if a given object implements the CategoryDTOPagedResponse interface.
 */
export function instanceOfCategoryDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CategoryDTOPagedResponseFromJSON(json: any): CategoryDTOPagedResponse {
    return CategoryDTOPagedResponseFromJSONTyped(json, false);
}

export function CategoryDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(CategoryDTOFromJSON)),
    };
}

export function CategoryDTOPagedResponseToJSON(value?: CategoryDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(CategoryDTOToJSON)),
    };
}

