/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CategoryDTOPagedResponse } from './CategoryDTOPagedResponse';
import {
    CategoryDTOPagedResponseFromJSON,
    CategoryDTOPagedResponseFromJSONTyped,
    CategoryDTOPagedResponseToJSON,
} from './CategoryDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CategoryDTOPagedResponseRequestResponse
 */
export interface CategoryDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {CategoryDTOPagedResponse}
     * @memberof CategoryDTOPagedResponseRequestResponse
     */
    response?: CategoryDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CategoryDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the CategoryDTOPagedResponseRequestResponse interface.
 */
export function instanceOfCategoryDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CategoryDTOPagedResponseRequestResponseFromJSON(json: any): CategoryDTOPagedResponseRequestResponse {
    return CategoryDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function CategoryDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : CategoryDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CategoryDTOPagedResponseRequestResponseToJSON(value?: CategoryDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': CategoryDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

