/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedbackFormDTO
 */
export interface FeedbackFormDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedbackFormDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedbackFormDTO
     */
    feedback?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FeedbackFormDTO
     */
    overallRating?: number;
    /**
     * 
     * @type {number}
     * @memberof FeedbackFormDTO
     */
    deliveryRating?: number;
    /**
     * 
     * @type {string}
     * @memberof FeedbackFormDTO
     */
    favoriteFeatures?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FeedbackFormDTO
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the FeedbackFormDTO interface.
 */
export function instanceOfFeedbackFormDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackFormDTOFromJSON(json: any): FeedbackFormDTO {
    return FeedbackFormDTOFromJSONTyped(json, false);
}

export function FeedbackFormDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackFormDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'feedback': !exists(json, 'feedback') ? undefined : json['feedback'],
        'overallRating': !exists(json, 'overallRating') ? undefined : json['overallRating'],
        'deliveryRating': !exists(json, 'deliveryRating') ? undefined : json['deliveryRating'],
        'favoriteFeatures': !exists(json, 'favoriteFeatures') ? undefined : json['favoriteFeatures'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function FeedbackFormDTOToJSON(value?: FeedbackFormDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'feedback': value.feedback,
        'overallRating': value.overallRating,
        'deliveryRating': value.deliveryRating,
        'favoriteFeatures': value.favoriteFeatures,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

