/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { FeedbackFormDTO } from './FeedbackFormDTO';
import {
    FeedbackFormDTOFromJSON,
    FeedbackFormDTOFromJSONTyped,
    FeedbackFormDTOToJSON,
} from './FeedbackFormDTO';

/**
 * 
 * @export
 * @interface FeedbackFormDTORequestResponse
 */
export interface FeedbackFormDTORequestResponse {
    /**
     * 
     * @type {FeedbackFormDTO}
     * @memberof FeedbackFormDTORequestResponse
     */
    response?: FeedbackFormDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof FeedbackFormDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the FeedbackFormDTORequestResponse interface.
 */
export function instanceOfFeedbackFormDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackFormDTORequestResponseFromJSON(json: any): FeedbackFormDTORequestResponse {
    return FeedbackFormDTORequestResponseFromJSONTyped(json, false);
}

export function FeedbackFormDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackFormDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : FeedbackFormDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function FeedbackFormDTORequestResponseToJSON(value?: FeedbackFormDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': FeedbackFormDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

