/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { FeedbackFormDTOPagedResponse } from './FeedbackFormDTOPagedResponse';
import {
    FeedbackFormDTOPagedResponseFromJSON,
    FeedbackFormDTOPagedResponseFromJSONTyped,
    FeedbackFormDTOPagedResponseToJSON,
} from './FeedbackFormDTOPagedResponse';

/**
 * 
 * @export
 * @interface FeedbackFormDTOPagedResponseRequestResponse
 */
export interface FeedbackFormDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {FeedbackFormDTOPagedResponse}
     * @memberof FeedbackFormDTOPagedResponseRequestResponse
     */
    response?: FeedbackFormDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof FeedbackFormDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the FeedbackFormDTOPagedResponseRequestResponse interface.
 */
export function instanceOfFeedbackFormDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackFormDTOPagedResponseRequestResponseFromJSON(json: any): FeedbackFormDTOPagedResponseRequestResponse {
    return FeedbackFormDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function FeedbackFormDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackFormDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : FeedbackFormDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function FeedbackFormDTOPagedResponseRequestResponseToJSON(value?: FeedbackFormDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': FeedbackFormDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

