/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FeedbackFormDTO } from './FeedbackFormDTO';
import {
    FeedbackFormDTOFromJSON,
    FeedbackFormDTOFromJSONTyped,
    FeedbackFormDTOToJSON,
} from './FeedbackFormDTO';

/**
 * 
 * @export
 * @interface FeedbackFormDTOPagedResponse
 */
export interface FeedbackFormDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof FeedbackFormDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof FeedbackFormDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof FeedbackFormDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<FeedbackFormDTO>}
     * @memberof FeedbackFormDTOPagedResponse
     */
    data?: Array<FeedbackFormDTO> | null;
}

/**
 * Check if a given object implements the FeedbackFormDTOPagedResponse interface.
 */
export function instanceOfFeedbackFormDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedbackFormDTOPagedResponseFromJSON(json: any): FeedbackFormDTOPagedResponse {
    return FeedbackFormDTOPagedResponseFromJSONTyped(json, false);
}

export function FeedbackFormDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedbackFormDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(FeedbackFormDTOFromJSON)),
    };
}

export function FeedbackFormDTOPagedResponseToJSON(value?: FeedbackFormDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(FeedbackFormDTOToJSON)),
    };
}

