/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeedBackFormAddDTO
 */
export interface FeedBackFormAddDTO {
    /**
     * 
     * @type {string}
     * @memberof FeedBackFormAddDTO
     */
    feedback?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FeedBackFormAddDTO
     */
    overallRating?: number;
    /**
     * 
     * @type {number}
     * @memberof FeedBackFormAddDTO
     */
    deliveryRating?: number;
    /**
     * 
     * @type {string}
     * @memberof FeedBackFormAddDTO
     */
    favoriteFeatures?: string | null;
}

/**
 * Check if a given object implements the FeedBackFormAddDTO interface.
 */
export function instanceOfFeedBackFormAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeedBackFormAddDTOFromJSON(json: any): FeedBackFormAddDTO {
    return FeedBackFormAddDTOFromJSONTyped(json, false);
}

export function FeedBackFormAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedBackFormAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'feedback': !exists(json, 'feedback') ? undefined : json['feedback'],
        'overallRating': !exists(json, 'overallRating') ? undefined : json['overallRating'],
        'deliveryRating': !exists(json, 'deliveryRating') ? undefined : json['deliveryRating'],
        'favoriteFeatures': !exists(json, 'favoriteFeatures') ? undefined : json['favoriteFeatures'],
    };
}

export function FeedBackFormAddDTOToJSON(value?: FeedBackFormAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'feedback': value.feedback,
        'overallRating': value.overallRating,
        'deliveryRating': value.deliveryRating,
        'favoriteFeatures': value.favoriteFeatures,
    };
}

