/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductUpdateDTO
 */
export interface ProductUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductUpdateDTO
     */
    price?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductUpdateDTO
     */
    stock?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateDTO
     */
    imageUrl?: string | null;
}

/**
 * Check if a given object implements the ProductUpdateDTO interface.
 */
export function instanceOfProductUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductUpdateDTOFromJSON(json: any): ProductUpdateDTO {
    return ProductUpdateDTOFromJSONTyped(json, false);
}

export function ProductUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'stock': !exists(json, 'stock') ? undefined : json['stock'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
    };
}

export function ProductUpdateDTOToJSON(value?: ProductUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'description': value.description,
        'price': value.price,
        'stock': value.stock,
        'imageUrl': value.imageUrl,
    };
}

