/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductAddDTO
 */
export interface ProductAddDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductAddDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductAddDTO
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductAddDTO
     */
    stock?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductAddDTO
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductAddDTO
     */
    color?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductAddDTO
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductAddDTO
     */
    categoryId?: string;
}

/**
 * Check if a given object implements the ProductAddDTO interface.
 */
export function instanceOfProductAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductAddDTOFromJSON(json: any): ProductAddDTO {
    return ProductAddDTOFromJSONTyped(json, false);
}

export function ProductAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'stock': !exists(json, 'stock') ? undefined : json['stock'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'color': !exists(json, 'color') ? undefined : json['color'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'categoryId': !exists(json, 'categoryId') ? undefined : json['categoryId'],
    };
}

export function ProductAddDTOToJSON(value?: ProductAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'price': value.price,
        'stock': value.stock,
        'size': value.size,
        'color': value.color,
        'imageUrl': value.imageUrl,
        'categoryId': value.categoryId,
    };
}

