/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
} from './UserRoleEnum';

/**
 * 
 * @export
 * @interface UserLoginDTO
 */
export interface UserLoginDTO {
    /**
     * 
     * @type {string}
     * @memberof UserLoginDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserLoginDTO
     */
    email?: string | null;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof UserLoginDTO
     */
    role?: UserRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof UserLoginDTO
     */
    cartId?: string;
}

/**
 * Check if a given object implements the UserLoginDTO interface.
 */
export function instanceOfUserLoginDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserLoginDTOFromJSON(json: any): UserLoginDTO {
    return UserLoginDTOFromJSONTyped(json, false);
}

export function UserLoginDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLoginDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'role': !exists(json, 'role') ? undefined : UserRoleEnumFromJSON(json['role']),
        'cartId': !exists(json, 'cartId') ? undefined : json['cartId'],
    };
}

export function UserLoginDTOToJSON(value?: UserLoginDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'role': UserRoleEnumToJSON(value.role),
        'cartId': value.cartId,
    };
}

