/* tslint:disable */
/* eslint-disable */
/**
 * SoleVault
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CartDTO } from './CartDTO';
import {
    CartDTOFromJSON,
    CartDTOFromJSONTyped,
    CartDTOToJSON,
} from './CartDTO';
import type { FeedbackFormDTO } from './FeedbackFormDTO';
import {
    FeedbackFormDTOFromJSON,
    FeedbackFormDTOFromJSONTyped,
    FeedbackFormDTOToJSON,
} from './FeedbackFormDTO';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
} from './UserRoleEnum';

/**
 * 
 * @export
 * @interface UserDTO
 */
export interface UserDTO {
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    email?: string | null;
    /**
     * 
     * @type {CartDTO}
     * @memberof UserDTO
     */
    cart?: CartDTO;
    /**
     * 
     * @type {FeedbackFormDTO}
     * @memberof UserDTO
     */
    feedbackForm?: FeedbackFormDTO;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof UserDTO
     */
    role?: UserRoleEnum;
}

/**
 * Check if a given object implements the UserDTO interface.
 */
export function instanceOfUserDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserDTOFromJSON(json: any): UserDTO {
    return UserDTOFromJSONTyped(json, false);
}

export function UserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'cart': !exists(json, 'cart') ? undefined : CartDTOFromJSON(json['cart']),
        'feedbackForm': !exists(json, 'feedbackForm') ? undefined : FeedbackFormDTOFromJSON(json['feedbackForm']),
        'role': !exists(json, 'role') ? undefined : UserRoleEnumFromJSON(json['role']),
    };
}

export function UserDTOToJSON(value?: UserDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'cart': CartDTOToJSON(value.cart),
        'feedbackForm': FeedbackFormDTOToJSON(value.feedbackForm),
        'role': UserRoleEnumToJSON(value.role),
    };
}

